name: ringtoon_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - icons/1.jpg
    - icons/2.jpg
    - icons/3.jpg
    - icons/4.jpg
    - icons/5.jpg
    - numbers/1.jpg
    - numbers/2.jpg
    - numbers/3.jpg
    - numbers/4.jpg
    - numbers/5.jpg
    - numbers/6.jpg
    - numbers/7.jpg
    - numbers/8.jpg
    - numbers/9.jpg
    - numbers/10.jpg
    - numbers/11.jpg
    - numbers/12.jpg
    - numbers/13.jpg
    - numbers/14.jpg
    - numbers/15.jpg
    - numbers/16.jpg
    - numbers/17.jpg
    - numbers/18.jpg
    - numbers/19.jpg
    - numbers/20.jpg

